export const projects = [
  {
    id: "moonup",
    role: "Faunder, Project Manager, FullStack Engineer",
    type: "(Web-app)",
    title: "MoonUp",
    dec: `MoonUp is a Company/business that focuses on staying up to date with emerging technological trends. We assist companies with a range of duties, including programming, developing solutions, maintaining and analyzing data, integrating systems, and safeguarding data.`,
    website: "https://app.moonup.uz",
    github: "https://github.com/IbrokhimWeb/IbrokhimWeb",
    image: "moonup.jpg",
    more: `MoonUp is a Company/business that focuses on staying up to date with emerging technological trends. We assist companies with a range of duties, including programming, developing solutions, maintaining and analyzing data, integrating systems, and safeguarding data. Developing excellent products and assisting staff in staying up to date with emerging technologies and procedures are our two main objectives.`,
    technologies: [
      "Reactjs",
      "Typescript",
      "TailwindCSS",
      "MaterialUI",
      "Apexcharts",
    ],
    date: new Date(),
  },
  {
    id: "innmall",
    role: "Frontend Developer",
    type: "(Web-site)",
    title: "InnMall",
    dec: "InnMall - Bu marketplace sotuvchi va xaridor uchrashadigan, mahsulot va xizmatlar oldi sotdisi amalga oshiriladigan qulay marketplace. Unda siz istalgan mahsulot yoki xizmatingizni sotishingiz yoki sotib olishingiz mumkin",
    website: "https://innmall.uz",
    github: "https://github.com/IbrokhimWeb/innmall",
    image: "innmall.jpg",
    more: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni aspernatur vitae at mollitia est tempore, ducimus dolor hic, dolores culpa, reprehenderit asperiores. Ducimus rerum quasi tempora. Tenetur omnis et dicta Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni aspernatur vitae at mollitia est tempore, ducimus dolor hic, dolores culpa, reprehenderit asperiores. Ducimus rerum quasi tempora. Tenetur omnis et dicta?",
    technologies: [
      "Reactjs",
      "Typescript",
      "TailwindCSS",
      "MaterialUI",
      "Yandex Metrika",
    ],
    date: new Date(),
  },
  {
    id: "sarbon",
    role: "Frontend Developer",
    type: "(Web-site)",
    title: "Sarbon",
    dec: "Har bir yirik kompaniya faqatgina oʻziga emas, balki yonida yelkadosh boʻlgan hamda ishonganlarga minnatdorchilik bildirishi lozim. Axir, bizning ishda eng muhim prinsip - bu ishonch.",
    website: "https://sarbon.vercel.app/",
    github: "https://github.com/IbrokhimWeb/old-sarbon",
    image: "sarbon.jpg",
    more: "Har bir yirik kompaniya faqatgina oʻziga emas, balki yonida yelkadosh boʻlgan hamda ishonganlarga minnatdorchilik bildirishi lozim. Axir, bizning ishda eng muhim prinsip - bu ishonch. Ishonch nafaqat mijoz va hamkorlar sadoqatini ta’minlaydi, qolversa, o’zimizga bo’lgan talabchanligimizni oshiradi. Biz uzoq yillik insoniylik an’analari ustiga qurilgan munosabatlar asosida hamkorlik qilamiz.",
    technologies: ["Nextjs", "Reactjs", "Typescript", "TailwindCSS"],
    date: new Date(),
  },
  {
    id: "marhamat",
    role: "Frontend Developer",
    type: "(Web-site)",
    title: "Marhamat",
    dec: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni aspernatur vitae at mollitia est tempore, ducimus dolor hic, dolores culpa, reprehenderit asperiores.",
    website: "https://marxamat.uz",
    github: "https://github.com/IbrokhimWeb/marhamat",
    image: "marhamat.jpg",
    more: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni aspernatur vitae at mollitia est tempore, ducimus dolor hic, dolores culpa, reprehenderit asperiores. Ducimus rerum quasi tempora. Tenetur omnis et dicta Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni aspernatur vitae at mollitia est tempore, ducimus dolor hic, dolores culpa, reprehenderit asperiores. Ducimus rerum quasi tempora. Tenetur omnis et dicta?",
    technologies: ["Reactjs", "Typescript", "TailwindCSS"],
    date: new Date(),
  },
];
